config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  # devise_for :users
  root to: 'pages#home'

  resources :profiles, only: [:show] do
    resources :orders, only: [:index]
  end

  get "/my_profile", to: "profiles#my_profile", as: "my_profile"

  resources :campaigns, except: [:show]
  get "campaigns/:id", to: "campaigns#verify_private_campaign", as: "verify_private_campaign"
  post "campaigns/:id", to: "campaigns#check_codeword", as: "check_codeword"
  get "new_ticket_category", to: "campaigns#new_ticket_category", as: "new_ticket_category"
  get "delete_ticket_category", to: "campaigns#delete_ticket_category", as: "delete_ticket_category"

  devise_for :users, controllers: { registrations: "registrations" }

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  resources :tickets, only: [:show, :update, :edit]

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :tickets, dependent: :destroy
  has_many :ticket_categories, through: :tickets

  monetize :amount_cents
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = current_user.orders.where(state: 'paid')
  end

  def show
    @order = current_user.orders.where(state: 'paid').find(params[:id])
    @campaigns = Campaign.order("RANDOM()").limit(3)
  end

  # def get_html
  #   render_to_string(
  #     template: "layouts/pdf.html.erb",
  #     orientation: "Landscape",
  #     page_size: "Letter",
  #     background: true,
  #     order: @order
  #     )
  # end

  def new
  end

  def create
    @order = Order.new
    @campaign = Campaign.find(order_params[:campaign_id])
    @order.user = current_user
    @order.state = 'pending'
    @categories = category_params.to_h.map { |key, value| [TicketCategory.find(key), value.to_i] }
    @order.amount = @categories.map { |category| category[1] * category[0].price }.sum
    @order.ticket_category_sku = @categories.map { |ids| ids[0].id }
    if @order.save
      @categories.each do |category|
        category[1].times do
          Ticket.create(order: @order, ticket_category: category[0])
        end
      end
      redirect_to new_order_payment_path(@order)
    else
      render 'campaigns/show'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def category_params
    params.require(:categories).permit!
  end

  def order_params
    params.require(:order).permit(:campaign_id)
  end
end

app/views/orders/index.html.erb
<div class="container container-top" style="padding-bottom: 100px;">
  <h1>My Pledges</h1>
  <div class="row">
    <% if @orders.size == 0 %>
      <h3>No Pledges Made!</h3>
    <% else %>
      <% @orders.each do |order| %>
        <div class="col-sm-12">
          <div class="list-card">
            <%= link_to campaign_path(order.ticket_categories.first.campaign), class: "list-card-link" do %>
            <% end %>
            <div class="list-card-photo" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)), url('<%= cl_image_path order.ticket_categories.first.campaign.photos.first.image_url, height: 200, width: 400, crop: :fill %>')">
              <div class="list-card-date">
                <p><%= order.ticket_categories.first.campaign.date.strftime("%^b") %></p>
                <h3><%= order.ticket_categories.first.campaign.date.strftime("%e") %></h3>
              </div>
            </div>
            <div class="list-card-text">
              <h4><%= order.ticket_categories.first.campaign.name %></h4>
              <p><%= order.ticket_categories.first.campaign.genre %> | <%= order.ticket_categories.first.campaign.address %></p>
              <div style="color: black;">
                Pledge Amount: <%= humanized_money_with_symbol(order.amount) %>
                <% if order.ticket_categories.first.campaign.current_funding_amount >= order.ticket_categories.first.campaign.funding_goal %>
                  <div class="btn-group">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Tickets <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                      <% counter = 1 %>
                      <% order.tickets.each do |ticket| %>
                        <li><%= link_to "Ticket #{counter}", ticket_path(ticket.id, :format => :pdf), target: :_blank %></li>
                        <% counter += 1 %>
                      <% end %>
                    </ul>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="list-card-status">
              <div class="progress-circle" data-progress="<%= (((order.ticket_categories.first.campaign.current_funding_amount).to_f / (order.ticket_categories.first.campaign.funding_goal).to_f) * 100).round %>">
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/orders/show.html.erb
<div class="container container-top">
  <div class="row">
    <div class="col-sm-12">
      <div class="order-success">
        <div class="order-success-title" >
          <i class="far fa-check-circle order-tick"></i>
          <h2><strong>Congratulations! Your Pledge has been a success!</strong></h2>
        </div>
        <div class="order-success-order-info">
          <h3>You contributed <%= humanized_money_with_symbol(@order.amount) %> toward a goal of <%= humanized_money_with_symbol(@order.ticket_categories.first.campaign.funding_goal) %></h3>
          <article>
            <label class="amount">
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Pledge Type</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Price per Pledge</th>
                  </tr>
                </thead>
                <tbody>
                  <% @order.tickets.group_by(&:ticket_category).each do |ticket_category, tickets| %>
                    <tr>
                      <td><%= ticket_category.name %></td>
                      <td><%= tickets.count %></td>
                      <td><%= ticket_category.price %></td>
                    </tr>
                  <% end %>
                </tbody>
                <td>Total Amount: <%= humanized_money_with_symbol(@order.amount) %></td>
              </table>
            </label>
          </article>
        </div>
        <%= link_to profile_orders_path(current_user) do %>
          <p class="btn btn-success">Track My Pledges <i class="fas fa-arrow-right"></i></p>
        <% end %>
      </div>
    </div>
  </div>
  <hr>
  <div class="other-campaigns-title">
    <h3><strong>Other Campaigns You Might Be Interested In:</strong></h3>
  </div>
  <%= render "components/campaigns_order_cards" %>
</div>