config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  # devise_for :users
  root to: 'pages#home'

  resources :profiles, only: [:show] do
    resources :orders, only: [:index]
  end

  get "/my_profile", to: "profiles#my_profile", as: "my_profile"

  resources :campaigns, except: [:show]
  get "campaigns/:id", to: "campaigns#verify_private_campaign", as: "verify_private_campaign"
  post "campaigns/:id", to: "campaigns#check_codeword", as: "check_codeword"
  get "new_ticket_category", to: "campaigns#new_ticket_category", as: "new_ticket_category"
  get "delete_ticket_category", to: "campaigns#delete_ticket_category", as: "delete_ticket_category"

  devise_for :users, controllers: { registrations: "registrations" }

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  resources :tickets, only: [:show, :update, :edit]

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_order

  def new
  end

  def create
    customer = Stripe::Customer.create(
      source: params[:stripeToken],
      email:  params[:stripeEmail]
    )

    charge = Stripe::Charge.create(
      customer:     customer.id,   # You should store this customer id and re-use it.
      amount:       @order.amount_cents,
      description:  "Help A Campaign!",
      currency:     @order.amount.currency
    )

    @categories_hash = @order.ticket_categories.group(:id).count
    @categories_hash.each do |key, value|
      @category = TicketCategory.find(key)
      new_available_tickets = @category.available_tickets - value
      @category.update(available_tickets: new_available_tickets)
    end
    @campaign = @order.ticket_categories.first.campaign

    @funding_array = @campaign.ticket_categories.map do |ticket_category|
      (ticket_category.quantity - ticket_category.available_tickets) * ticket_category.price
    end
    @campaign.update(current_funding_amount: @funding_array.sum)
    @order.update(payment: charge.to_json, state: 'paid')

    redirect_to order_path(@order)
  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_order_payment_path(@order)
  end

  def show
    @order = current_user.orders.where(state: 'paid').find(params[:id])
  end

  private

  def set_order
    @order = current_user.orders.where(state: 'pending').find(params[:order_id])
  end
end

app/views/payments/new.html.erb
<div class="container" style="margin-top: 100px;">
  <h2><strong>Your Order Summary:</strong></h2>
  <hr>
  <div class="row">
    <%= form_tag order_payments_path(@order) do %>
      <div class="col-sm-8">
        <% @order.tickets.group_by(&:ticket_category).each do |ticket_category, tickets| %>
          <div class="list-card payment-card">
            <div class="list-card-photo" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)), url('<%= cl_image_path ticket_category.campaign.photos.first.image_url, height: 200, width: 400, crop: :fill %>')">
            </div>
            <div class="list-card-text">
              <h4><%= ticket_category.campaign.name %></h4>
                <h5>Pledge type: <%= ticket_category.name %></h5>
                <p>Quantity: <%= tickets.count %></p>
                <p>Price: <%= humanized_money_with_symbol(ticket_category.price)%></p>
            </div>
          </div>
        <hr>
        <% end %>
      </div>
      <div class="col-sm-4 payment-order-stripe">
        <h5><%= @order.ticket_categories.count %> <% if @order.ticket_categories.count == 1 %> Pledge <% else %>Pledges<% end %> in Total</h5>
        <h4>Subtotal: <%= humanized_money_with_symbol(@order.amount) %></h4>
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
        data-name="<%= current_user.first_name %>'s Pledge Towards:"
        data-email="<%= current_user.email %>"
        data-description="<%= @order.ticket_categories.first.campaign.name  %>"
        data-amount="<%= @order.amount_cents %>"
        data-currency="<%= @order.amount.currency %>">
        </script>
      </div>
    <% end %>
  </div>
</div>