config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  # devise_for :users
  root to: 'pages#home'

  resources :profiles, only: [:show] do
    resources :orders, only: [:index]
  end

  get "/my_profile", to: "profiles#my_profile", as: "my_profile"

  resources :campaigns, except: [:show]
  get "campaigns/:id", to: "campaigns#verify_private_campaign", as: "verify_private_campaign"
  post "campaigns/:id", to: "campaigns#check_codeword", as: "check_codeword"
  get "new_ticket_category", to: "campaigns#new_ticket_category", as: "new_ticket_category"
  get "delete_ticket_category", to: "campaigns#delete_ticket_category", as: "delete_ticket_category"

  devise_for :users, controllers: { registrations: "registrations" }

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  resources :tickets, only: [:show, :update, :edit]

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :user
  has_many :performances, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :ticket_categories, dependent: :destroy

  has_many :musicians, through: :performances
  has_many :tickets, through: :ticket_categories, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :date, presence: true
  validates :genre, inclusion: { in: ["Pop", "Rock 'n' Roll", "Rap / Hip-hop Music", "Techno", "House", "Alternative / Indie (Rock)", "Trance", "Downtempo / Ambient", "Electronic", "Industrial & Gothic", "(Heavy) Metal", "Golden Age", "Punk (Rock) / (New) Wave", "Hardcore (Punk)", "Contemporary (Rock)", "Country", "Rhythm 'n' Blues (R&B)", "Gospel & Pioneers", "Blues", "Jazz", "Jamaican (Music) / Reggae", "Breakbeat", "Drum 'n' Bass / Jungle", "Hardcore (Techno)"] }

  accepts_nested_attributes_for :performances
  accepts_nested_attributes_for :ticket_categories

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy, :verify_private_campaign, :check_codeword]
  before_action :campaigns_backed, only: [:index, :show, :verify_private_campaign, :check_codeword]
  before_action :campaign_days_left, only: [:show, :verify_private_campaign, :check_codeword]

  skip_before_action :authenticate_user!, only: [:index, :show, :verify_private_campaign, :check_codeword]

  def index
    @campaigns = Campaign.where(is_private: false)
    if params[:name_query].present?
      @campaigns = @campaigns.where(
        "name @@ :name_query OR description @@ :name_query",
        name_query: "%#{params[:name_query]}%"
      )
    end

    if params[:location_query] == ''
      @campaigns = @campaigns.where.not(latitude: nil, longitude: nil)
    elsif params[:location_query]
      @campaigns = @campaigns.near(params[:location_query], 20)
    end

    if params[:musician_query].present? && params[:musician_query] != "any musician" && params[:musician_query] != "All musicians"
      musician = Musician.find(params[:musician_query])
      @campaigns = @campaigns.joins(:performances).where({ performances: { musician: musician } })
    end

    if params[:genre_query].present? && params[:genre_query] != "all" && params[:genre_query] != "All genres"
      @campaigns = @campaigns.where(
        "genre @@ :genre_query",
        genre_query: "%#{params[:genre_query]}%"
      )
    end

    @markers = @campaigns.map do |campaign|
      {
        lng: campaign.longitude,
        lat: campaign.latitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { campaign: campaign })
      }
    end
    render :index
  end

  def show
    @campaign = Campaign.find(params[:id])
    @campaign_creator = User.find(@campaign.user_id)
  end

  def new
    @campaign = Campaign.new
    @campaign_images = @campaign.photos.build
    @ticket_categories = params[:ticket_categories].nil? ? [TicketCategory.new] : params[:ticket_categories]
  end

  def create
    @campaign = Campaign.new(campaign_params)
    @campaign.user = current_user
    instance_array = []
    if @campaign.codeword != nil
      @campaign.is_private = true
    end
    if params[:ticket_categories].count.positive? && params[:campaign][:performances].count > 1 && params[:campaign][:photos]['image_url'] && @campaign.save
      params[:ticket_categories].each do |ticket_category|
        category = @campaign.ticket_categories.new(
          name: ticket_category[:name],
          description: ticket_category[:description],
          quantity: ticket_category[:quantity],
          price: ticket_category[:price],
          available_tickets: ticket_category[:quantity]
        )
        instance_array << category
      end

      params[:campaign][:photos]['image_url'].each do |cloudinary_url|
        @campaign.photos.create(image_url: cloudinary_url)
      end

      params[:campaign][:performances].each do |performance|
        if performance.match(/^[0-9]+$/) && Musician.exists?(performance.to_i)
          performance_instance = @campaign.performances.new(musician: Musician.find(performance.to_i))
          instance_array << performance_instance
        elsif performance.length >= 1
          @musician = Musician.new(name: performance)
          instance_array << @musician
          performance_instance = Performance.new(campaign: @campaign, musician: @musician)
          instance_array << performance_instance
        end
      end

      if instance_array.all?(&:valid?)
        instance_array.each(&:save!)
        redirect_to campaign_path(@campaign)
      end
    else
      # Send a variable to the new action that contains the amount of simplefields partials we need to render.
      @params = params[:ticket_categories].map do |ticket_category|
        TicketCategory.new(
          name: ticket_category[:name],
          description: ticket_category[:description],
          quantity: ticket_category[:quantity],
          price: ticket_category[:price],
          available_tickets: ticket_category[:quantity]
        )
      end
      @ticket_categories = params[:ticket_categories].nil? ? [TicketCategory.new] : @params
      render :new
    end
  end

  def edit
    if current_user != @campaign.user
      redirect_to root_path
      flash[:alert] = 'Not Gonna Happen'
    end
    @campaign = Campaign.find(params[:id])

  end

  def update
    @campaign.update(campaign_params)
    redirect_to my_profile_path
  end

  def destroy
    @campaign.destroy
    redirect_to my_profile_path
  end

  def new_ticket_category
    @ticket_category = TicketCategory.new
  end

  def delete_ticket_category
  end

  def verify_private_campaign
    @campaign_creator = User.find(@campaign.user_id)

    render :show if @campaign.is_private == false || current_user == @campaign_creator
  end

  def check_codeword
    @campaign_creator = User.find(@campaign.user_id)

    if params[:codeword][:input] == @campaign.codeword
      render :show
    else
      redirect_to verify_private_campaign_path
      flash[:alert] = 'Please enter the correct codeword.'
    end
  end

  private

  def set_campaign
    @campaign = Campaign.find(params[:id])
  end

  def campaign_params
    params.require(:campaign).permit(:name, :address, :description, :date, :url, :is_private?, :genre, :funding_goal, :campaign_end_date, :codeword)
  end

  def campaigns_backed
    @campaigns_backed = TicketCategory.joins(:orders).where({ orders: { user_id: current_user } }).map { |campaign| campaign.campaign_id }
  end

  def campaign_days_left
    @campaign_days_left = (@campaign.campaign_end_date - DateTime.now + 1).to_i
    if @campaign.campaign_end_date > DateTime.now
      @campaign_active = true
    else
      @campaign_active = false
    end
  end
end

app/views/campaigns/_infowindow.html.erb
<div class="mapboxgl-popup">
  <div class="mapboxgl-popup-content">
    <%= cl_image_tag campaign.photos.first.image_url, width: 200, crop: :fill %>
    <h5><%= campaign.name %></h5>
    <p>
      <%= campaign.genre %> |
      <%= campaign.address %> |
      <%= campaign.date.strftime("%e-%m-%y") %>
    </p>
    <%= link_to "Pledge!", campaign_path(campaign), class: 'btn green-button'  %>
  </div>
</div>

app/views/campaigns/delete_ticket_category.js.erb
function deleteHTMLOption() {
  document
    .getElementById("addTicketCategory")
    .insertAdjacentHTML('beforebegin', formHTML);
};

createHTMLOptions();

app/views/campaigns/edit.html.erb
<head>
  <title>Edit Crowdbook crowdfunding campaign </title>
  <meta property="og:title" content="">
  <meta property="og:description" content="">
  <meta property="og:type" content="">
  <meta property="og:url" content="">
  <meta property="og:image" content="">
</head>
<div class="login-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.7) 0%, rgba(0,36,61,0.7) 50%), url(' https://source.unsplash.com/collection/572418/1600x800');">
</div>
<div class="container" style="min-height: 70vh;margin: 0 auto;">
  <div class="signup-form-container">
    <center><h3 style="margin-bottom: 20px;">Update Campaign <%= @campaign.name %></h3></center>
      <%= simple_form_for @campaign do |f| %>
        <%= f.input :address%>
        <%= f.input :description, as: :text %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
  </div>
</div>

app/views/campaigns/index.html.erb
<div class="searchbar">
  <div class="container">
    <div class="row">
      <%= form_tag campaigns_path, method: :get, class: "form-inline" do %>
        <div class="col-xs-12 col-sm-2 searchbar-columns">
          <div class="search-box-column">
            <%= text_field_tag :name_query,
              params[:name_query],
              class: "form-control input",
              placeholder: "Name",
              style: "width: 100%;"
            %>
            <span class="fas fa-search search-box-column-icon"></span>
          </div>
        </div>
        <div class="col-xs-12 col-sm-2 searchbar-columns">
          <div class="search-box-column">
            <%= text_field_tag :location_query,
              params[:location_query],
              class: "form-control input",
              placeholder: "Location",
              style: "width: 100%;"
            %>
            <span class="fas fa-map-marker-alt search-box-column-icon"></span>
          </div>
        </div>
        <div class="col-xs-12 col-sm-2 searchbar-columns">
          <% collection = Musician.all.collect { |p| [p.name, p.id] } %>
          <% collection.unshift("All musicians") %>
          <%= select_tag :musician_query, options_for_select(collection, params[:musician_query]), class: "js-genre-selection-search" %>
        </div>
        <div class="col-xs-12 col-sm-2 searchbar-columns">
          <% collection =  ["All genres", "Pop", "Rock 'n' Roll", "Rap / Hip-hop Music", "Techno", "House", "Alternative / Indie (Rock)", "Trance", "Downtempo / Ambient", "Electronic", "Industrial & Gothic", "(Heavy) Metal", "Golden Age", "Punk (Rock) / (New) Wave", "Hardcore (Punk)", "Contemporary (Rock)", "Country", "Rhythm 'n' Blues (R&B)", "Gospel & Pioneers", "Blues", "Jazz", "Jamaican (Music) / Reggae", "Breakbeat", "Drum 'n' Bass / Jungle", "Hardcore (Techno)"] %>
          <%= select_tag :genre_query, options_for_select(collection, params[:genre_query]), class: "js-genre-selection-search" %>
        </div>
        <div class="col-xs-12 col-sm-2 searchbar-columns">
          <%= submit_tag 'Search', class: "green-button" %>
        </div>
      <% end %>
      <div class="col-xs-12 col-sm-2 searchbar-columns">
        <%= link_to "Cards", "#", :id => "toggleCards", :class => "cards-button active-toggle" %><%= link_to "Map", "#", :id => "toggleMap", :class => "map-button js-should-refresh-map" %>
      </div>
    </div>
  </div>
</div>

<div id="campaignCards" class="container container-index index_content active">
  <%= render "components/campaigns_index_cards" %>
</div>
<div id="campaignMap" class="container container-index index_content">
  <div class="map-div"><%= render "components/campaign_map" %></div>
</div>

app/views/campaigns/new.html.erb
<div class="container" style="margin-top: 90px;">
  <h1>Create a new campaign to fund your event!</h1>
  <%= simple_form_for @campaign do |f| %>
    <div class="form-row">
      <div class="form-group col-xs-12">
        <%= f.input :name, placeholder: "Please enter the name of your campaign", input_html: {class: "input"} %>
      </div>
      <div class="form-group col-xs-4">
        <%= f.simple_fields_for :photos do |p| %>
          <%= p.input :image_url, label: "Images", as: :file, input_html: { multiple: true, class: "input" } %>
          <%= p.input :image_url_cache, as: :hidden %>
        <% end %>
      </div>
      <div class="form-group col-xs-12 col-sm-4">
        <%= f.input :campaign_end_date, as: :string, input_html: {:id => "datepicker"}, placeholder: "Pick the end date of your campaign" %>
      </div>
      <div class="form-group col-xs-12 col-sm-12">
        <%= f.input :description, placeholder: "Please describe your campaign.", input_html: {class: "input"} %>
      </div>
    </div>
    <div class="row">
      <div class="form-group col-xs-12 col-sm-4">
        <%= f.input :address, placeholder: "Please enter the address of the venue for the event.", input_html: {class: "input"} %>
      </div>
      <div class="form-group col-xs-12 col-sm-4">
        <%= f.input :date, as: :string, input_html: {:id => "datepicker"}, placeholder: "Pick the date of your event" %>
      </div>
      <div class="form-group col-xs-12 col-sm-4">
        <%= f.input :url, placeholder: "Please enter your website or social media link.", input_html: {class: "input"} %>
      </div>
    </div>
    <div class="row">
      <div class="form-group col-xs-12 col-sm-4">
        <% collection =  ["Pop", "Rock 'n' Roll", "Rap / Hip-hop Music", "Techno", "House", "Alternative / Indie (Rock)", "Trance", "Downtempo / Ambient", "Electronic", "Industrial & Gothic", "(Heavy) Metal", "Golden Age", "Punk (Rock) / (New) Wave", "Hardcore (Punk)", "Contemporary (Rock)", "Country", "Rhythm 'n' Blues (R&B)", "Gospel & Pioneers", "Blues", "Jazz", "Jamaican (Music) / Reggae", "Breakbeat", "Drum 'n' Bass / Jungle", "Hardcore (Techno)"] %>
        <p style="font-size: 18px; font-weight: 700;">Genre</p>
        <%= f.select :genre, collection, {}, :class => 'js-genre-selection-form', required: true %>
      </div>
      <div class="form-group col-xs-12 col-sm-4">
        <p style="font-size: 18px; font-weight: 700;">Funding Goal</p>
        <%= f.input :funding_goal, placeholder: "Please enter your funding goal.", label: false, input_html: {class: "input"}  %>
      </div>
      <div id="checkbox_div" class="form-group col-xs-12 col-sm-4">
        <p style="font-size: 18px; font-weight: 700;">Private campaign</p>
        <%= f.input :is_private, id: "campaign_is_private", label: "Select if you want your campaign to be private", label_html: { class: "label-checkbox" }, as: :boolean %>
      </div>
    </div>
    <% musicians = Musician.all.collect { |p| [p.name, p.id] } %>
    <div class="form-row">
      <div class="form-group col-xs-12">
        <p style="font-size: 18px; font-weight: 700;">Add musicians that are playing at your event!</p>
        <%= f.select :performances, musicians, {}, :class => 'js-new-performance-form', :multiple => "multiple", required: true %>
      </div>
    </div>
    <div class="form-row">
      <% @ticket_categories.each do |ticket_category| %>
        <%= render 'components/ticket_category_form', ticket_category: ticket_category %>
      <% end %>
      <div id="addTicketCategory" class="form-group col-xs-12" style="margin-top: 20px;">
        <%= link_to "Add new ticket category", new_ticket_category_path, :class => "btn btn-success button", remote: true %>
        <%= f.button :submit, class: "btn btn-primary button", data: { disable_with: false } %>
      </div>
    </div>
  <% end %>
</div>

app/views/campaigns/new_ticket_category.js.erb
function createHTMLOptions() {
  const formHTML = `<%= j render 'components/ticket_category_form', ticket_category: TicketCategory.new %>`;
  document
    .getElementById("addTicketCategory")
    .insertAdjacentHTML('beforebegin', formHTML);
};

createHTMLOptions();

app/views/campaigns/show.html.erb
<head>
  <% content_for :meta_title, "#{@campaign.name} is on #{DEFAULT_META["meta_crowdbook"]}" %>
  <% content_for :meta_description, @campaign.description %>
  <% content_for :meta_image, cl_image_path(@campaign.photos.first.image_url) %>
</head>
<div class="wrapper-dark-green">
  <div class="container container-top">
    <% if @campaign.is_private == true %>
      <div class="row">
        <div class="col-sm-12 campaign-show-is-private">
          <h2>Shhhh... This is a private campaign!</h2>
          <% if (@campaign.is_private == true) && (@campaign.user == current_user) %>
          <h3>Your Private Codeword is: <strong><%= @campaign.codeword %></strong></h3>
          <% end %>
        </div>
      </div>
    <% end %>
    <% if @campaign_active == false %>
      <div class="row">
        <div class="col-sm-12 campaign-show-ended">
           <h2>Sorry, this Campaign is no longer active!</h2>
        </div>
      </div>
    <% end %>
    <% if @campaigns_backed.include?(@campaign.id)%>
    <div class="row">
      <div class="col-sm-12 campaign-show-backed">
         <h2><i class="far fa-check-circle"></i> Campaign Backed!</h2>
      </div>
    </div>
    <% end %>
    <div class="row campaign-head">
      <div class="col-sm-2">
        <div class="user-info">
          <%= link_to profile_path(@campaign.user_id) do %>
            <div class="avatar" style="background-image: url('<%= cl_image_path @campaign.user.profile_picture %>');"></div>
            <h5>By <%= @campaign_creator.first_name %> <%= @campaign_creator.last_name %></h5>
          <% end %>
        </div>
      </div>
      <div class="col-sm-9">
        <h1 style="margin: 0;"><%= @campaign.name %></h1>
        <h5>
          <%= @campaign.date %> |
          <%= @campaign.address %>
        </h5>
      </div>
    </div>
  </div>
</div>
<div class="wrapper-light-grey">
  <div class="container">
    <div class="row campaign-body">
      <div class="col-sm-8">
        <div class="campaign-photos">
          <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <% if @campaign.photos.count > 1 %>
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <% @campaign.photos[1..-1].each_with_index do |photo, index| %>
                  <li data-target="#carousel-example-generic" data-slide-to="<%= index + 1 %>"></li>
                <% end %>
              <% end %>
            </ol>
            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
              <div class="item gallery-image-parent active" style="background-image: url('<%= cl_image_path @campaign.photos.first.image_url, height: 450, width: 900, radius: 12, crop: :fill %>')"></div>
              <% if @campaign.photos.count > 1 %>
                <% @campaign.photos[1..-1].each do |photo| %>
                  <div class="item gallery-image-parent" style="background-image: url('<%= cl_image_path photo.image_url, height: 450, width: 900, radius: 12, crop: :fill %>')"></div>
                <% end %>
              <% end %>
            </div>

            <!-- Controls -->
            <% if @campaign.photos.count > 1 %>
              <a class="left carousel-control carousel-control-areas" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control carousel-control-areas" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            <% end %>
          </div>
        </div>
        <div class="campaign-description">
          <%= @campaign.description %>
        </div>
      </div>
      <div class="row responsive">
        <div class="col-sm-12">
          <div class="ticket-category-boxes" style="text-align: center;">
            <div class="progress-circle" data-progress="<%= (((@campaign.current_funding_amount).to_f / (@campaign.funding_goal).to_f) * 100).round %>">
            </div>
            <h4>Amount Pledged: <%= humanized_money_with_symbol(@campaign.current_funding_amount) %></h4>
            <h5>The Goal is <%= humanized_money_with_symbol(@campaign.funding_goal) %></h5>
            <h5><%= @campaign.tickets.count %> <% if @campaign.tickets.count == 1 %> Pledge <% else %> Pledges <% end %> Made</h5>
            <h4><%= @campaign_days_left %> <% if @campaign_days_left == 1 %> Day <% else %> Days <% end %> Left</h4>
          </div>
          <% if @campaign_active == true %>
            <%= simple_form_for :order, url: orders_path do |f| %>
              <%= f.input :campaign_id, as: :hidden, :input_html => { :value => @campaign.id } %>
                <%= simple_fields_for :categories do |c| %>
                  <% @campaign.ticket_categories.each do |category| %>
                    <div class="col-sm-3 ticket-category-boxes">
                      <p><strong><%= category.available_tickets %></strong> <% if category.available_tickets == 1 %> Ticket <% else %> Tickets <% end %> Left</p>
                      <h4><%= category.name %> | <%= humanized_money_with_symbol(category.price) %></h4>
                      <p><small><%= category.description %></small></p>
                      <% if category.available_tickets > 1 %>
                        <%= c.input "#{category.id}", collection: ((1..category.available_tickets).first(5)), label: "Quantity" %>
                      <% else %>
                        <%= c.input "#{category.id}", label: "Quantity", :disabled => true %>
                      <% end %>
                    </div>
                  <% end %>
                  <div style="text-align: center;">
                    <% if @campaign.ticket_categories.count >= 1 %>
                      <%= f.submit 'Purchase', class: 'btn btn-primary green-button' %>
                    <% else %>
                    <h4>No Tickets Available!</h4>
                    <% end %>
                  </div>
                <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/campaigns/verify_private_campaign.html.erb
<div class="container">
  <div class="row" style="margin-top: 150px;">
    <div class="col-sm-12">
      <h1>Please enter the codeword for this Campaign</h1>
      <%= simple_form_for :codeword, url: check_codeword_path do |f| %>
        <%= f.input :input %>
      <% end %>
    </div>
  </div>
</div>